FROM artifactory.nioint.com/dd-venus-docker-virtual/base/rockylinux/rockylinux8.7python3.12:1.0

RUN yum install mariadb-devel libjpeg-devel libpng-devel libtiff-devel freetype-devel zlib-devel -y

RUN pip3 install fastapi==0.90.0 loguru==0.6.0 sqlalchemy==1.4.43 passlib[bcrypt]==1.7.4 python-jose[cryptography]==3.3.0 typer[all]==0.7.0 uvicorn==0.19.0 email-validator==1.3.0 python-multipart==0.0.5 python-dotenv==0.21.0 appdirs==1.4.4 aiofiles==22.1.0 pillow==9.3.0 alembic==1.9.4 httpx==0.27.0 tfrecord==1.14.5 websockets==10.0.0 ffmpeg-python==0.2.0 APScheduler==3.11.0 mysqlclient==2.1.1 -i https://artifactory.nioint.com/artifactory/api/pypi/dd-pypi-all-virtual/simple

WORKDIR /app
